export const words = {
  apple: "яблуко",
  banana: "банан",
  cherry: "вишня",
  date: "фінік",
  elderberry: "бузина",
  fig: "інжир",
  grape: "виноград",
  honeydew: "диня",
  kiwi: "ківі",
  lemon: "лимон",
  mango: "манго",
  nectarine: "нектарин",
  orange: "апельсин",
  papaya: "папая",
  peach: "персик",
  pear: "груша",
  plum: "слива",
  raspberry: "малина",
  strawberry: "полуниця",
  watermelon: "кавун"
};
